#source ~/.config/zsh/ohmyzsh
source ~/.config/zsh/ps1
source ~/.config/zsh/aliases
source ~/.config/zsh/aliases_work
source ~/.path_variables
source ~/.config/zsh/atuin
source ~/.project_variables

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

HISTFILE=~/.zsh_history
HISTSIZE=20000

export PATH="$HOME/.poetry/bin:$PATH"
export TERMINAL=uxterm-256color
export EDITOR=nvim

source ~/.config/zsh/completion.zsh
