config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  d_ssh:
    src: ssh
    dst: ~/.ssh
    chmod: '700'
  f_input.conf:
    src: config/mpv/input.conf
    dst: ~/.config/mpv/input.conf
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
profiles:
  mspahn-work:
    dotfiles:
    - d_config_nvim
    - d_config_zsh
    - f_zshrc
    - f_gitconfig
    - d_git
    - d_ssh
    - f_input.conf
    - d_i3
    - d_i3status
    - d_atuin
  archlinux:
    dotfiles:
    - d_config_zsh
    - d_config_nvim
    - d_i3status
    - d_atuin
