config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  d_ssh:
    src: ssh
    dst: ~/.ssh
    chmod: '700'
profiles:
  mspahn-work:
    dotfiles:
    - d_config_nvim
    - d_config_zsh
    - f_zshrc
    - f_gitconfig
    - d_git
    - d_ssh
