config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_shell:
    src: config/shell
    dst: ~/.config/shell
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  f_ssh:
    src: ssh/config
    dst: ~/.ssh/config
  f_input.conf:
    src: config/mpv/input.conf
    dst: ~/.config/mpv/input.conf
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
profiles:
  mspahn-work:
    variables:
      ros_version: noetic
      phd: true
      shell_setup: ohmyzsh
    dotfiles:
    - d_config_shell
    - d_config_nvim
    - f_zshrc
    - f_gitconfig
    - d_git
    - f_ssh
    - f_config
  archlinux:
    variables:
      ros_version: None
      phd: true
      shell_setup: raw
    dotfiles:
    - d_config_nvim
    - d_config_shell
    - f_zshrc
    - f_gitconfig
    - d_git
    - f_ssh
    - f_input.conf
    - d_i3
    - d_i3status
    - d_atuin
  cluster:
    variables:
      ros_version: None
      phd: false
      shelll_setup: bash
    dotfiles:
    - d_config_nvim
    - d_config_shell
    - f_bashrc
    - f_gitconfig
    - d_git
    - f_ssh
    - f_input.conf
  debug:
    dotfiles:
    - d_config_shell
    variables:
      ros_version: noetic
      phd: true
      shell_setup: ohmyzsh
