config:
  backup: true
  create: true
  dotpath: dotfiles
  instignore:
  - '*.swp'
dotfiles:
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_nvim_win:
    src: config/nvim-win
    dst: ~/.config/nvim
  d_config_shell:
    src: config/shell
    dst: ~/.config/shell
  f_tmux:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  f_ssh:
    src: ssh/config
    dst: ~/.ssh/config
  f_input.conf:
    src: config/mpv/input.conf
    dst: ~/.config/mpv/input.conf
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_gitignore:
    src: config/git/gitignore
    dst: ~/.config/git/gitignore
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_default.json:
    src: mnt/c/Users/DEMASPA1/AppData/Local/Microsoft/PowerToys/Keyboard 
      Manager/default.json
    dst: /mnt/c/Users/DEMASPA1/AppData/Local/Microsoft/PowerToys/Keyboard 
      Manager/default.json
    chmod: '777'
  f_atuin.toml:
    src: config/atuin/config.toml
    dst: ~/.config/atuin/config.toml
    chmod: '600'
profiles:
  mspahn-work:
    variables:
      ros_version: noetic
      phd: true
      shell_setup: ohmyzsh
      poetry: true
      pyenv: true
      atuin: false
    dotfiles:
    - d_config_shell
    - d_config_nvim
    - f_zshrc
    - f_gitconfig
    - f_gitignore
    - d_git
    - f_ssh
    - f_ssh_config
  wsl:
    variables:
      poetry: false
      pyenv: true
      atuin: true
      phd: false
      ros_version: rolling
      shell_setup: zsh
    dotfiles:
    - d_config_shell
    - d_config_nvim
    - f_tmux
    - f_zshrc
    - f_gitconfig
    - f_gitignore
    - d_git
    - f_ssh_config
    - f_starship.toml
    - f_atuin.toml
    - f_default.json
  archlinux:
    variables:
      poetry: true
      pyenv: true
      atuin: true
      ros_version: None
      phd: true
      shell_setup: zsh
    dotfiles:
    - d_config_nvim
    - d_config_shell
    - f_zshrc
    - f_gitconfig
    - f_gitignore
    - d_git
    - f_ssh
    - f_input.conf
    - d_i3
    - d_i3status
    - d_atuin
    - d_config_nvim
  cluster:
    variables:
      poetry: false
      pyenv: false
      ros_version: None
      phd: false
      shell_setup: bash
      atuin: false
    dotfiles:
    - d_config_nvim
    - d_config_shell
    - f_bashrc
    - f_gitconfig
    - f_gitignore
    - d_git
    - f_ssh
    - f_inputrc
    - f_input.conf
