config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/config/tmux/tmux.conf
  d_nvim:
    src: config/nvim
    dst: ~/config/nvim
profiles:
  max-private:
    dotfiles:
    - f_zshrc
    - f_tmux.conf
    - d_nvim
